### ISSUE TITLE
`type` annotation in expression

### ISSUE THREAD

**Issue by dalance** [dalance/veryl#106]
In expression, type can be used:

```
parameter TYPE: type = u32;
parameter TYPE: type = logic<10>;
parameter TYPE: type = struct_a<10>;
parameter TYPE: type = enum_b<10>;
```

This causes parsing difficulty because identifier ( eg. `struct_a` `enum_b` )  may be normal variable.
How about explicit `type` annotation like below?

```
parameter TYPE: type = type u32;
parameter TYPE: type = type logic<10>;
parameter TYPE: type = type struct_a<10>;
parameter TYPE: type = type enum_b<10>;
```

**Comment by taichi-ishitani** [comment]
I think a type expression can be appered only at a parameter/localparam declaration with the `type` keyword.
How about dividing the parsing rule of a statement into a normal statement and a `type` related statement?
