### ISSUE TITLE
remove () in always_ff

### ISSUE THREAD

**Issue by dalance** [dalance/veryl#12]
Removing () in always_ff is uniform as `if` statement.

```
always_ff (clk) {
}
always_ff (clk, rst) {
}
always_ff (posedge clk, async_low rst) {
}
```

to

```
always_ff clk {
}
always_ff clk, rst {
}
always_ff posedge clk, async_low rst {
}
```

**Comment by AlphaLyrae0** [comment]
What about removing { and } as well ? I'd prefer indent based block recognition like Python.

**Comment by dalance** [comment]
> How about removing { and } as well ? I'd prefer indent based block recognition like Python.

Indent style like Python is very difficult to implement stable parser and formatter.
I think improving tool implementation smoothly is better than key typing reduction.

**Comment by dalance** [comment]
If reset exists (especially polarity exists), removing () may be hard to read.
