### ISSUE TITLE
[Feature] outside operator

### ISSUE THREAD

**Issue by taichi-ishitani** [dalance/veryl#124]
How about introducing `outside` operator?
This operator is negative version of `inside` oeraptr.

```
a = b outside {[0:1]}; // a = !(b inside {[0:1]});
```

**Comment by dalance** [comment]
Looks good.
I'll add `outside` at the same time as `inside`.

**Comment by taichi-ishitani** [comment]
#147 was created for `outside` expression support so I'm closing this issue.
