### ISSUE TITLE
Part select using position and width

### ISSUE THREAD

**Issue by taichi-ishitani** [dalance/veryl#30]
Part select using position and width (`a[pos+:WIDTH]`/`a[pos-:WIDTH]`) is useful feature.
So I'd like you to import this feature to veryl.

In addition, I think part select using index and width like below is a code showing often.

```systemverilog
b = a[2*i+:2];
```

Therefore, I'd like you to introduce a syntax sugger for this code like below.

```
b = a[2, i]; // a[2*i+:2]
```

**Comment by dalance** [comment]
`[2, i]` or `[i, 2]` may be confusable.
It means "index i @ step 2", so how about `[i step 2]` or `[i width 2]`

**Comment by taichi-ishitani** [comment]
`step` has already been used as a keyword so I think `[i step 2]` is better notation.

**Comment by dalance** [comment]
Added `+:` `-:` and `step`
