### ISSUE TITLE
[Bug] Incorrect scoping of package dependencies

### ISSUE THREAD

**Issue by nblei** [dalance/veryl#336]
Suppose you have dependency `foo` with package `bar`.

Then Veryl syntax to access an element in `bar` is

```
module a {
     localparam x: u32 = foo::bar::x;
}
```

The SV imported for the package is
```
package foo_bar;
...
```
However,
the emitted Veryl for module `a` is
```
module a;
    localparam int unsigned x = foo::bar::x;
endmodule
```
When it should be `foo_bar::x`.

**Comment by dalance** [comment]
Thank you for your report.
It was fixed through #459 .
