### ISSUE TITLE
Loop statement support

### ISSUE THREAD

**Issue by taichi-ishitani** [dalance/veryl#5]
My existing SV code includes loop statements such as for loop and while loop so I'd like Veryl to support these statements.

I think SV (C lang) style for loop statement is very bother notation because there are many similar code for example  `int i = 0;` and `++i;`. So I'd like you to introduce simple notation.

**Comment by dalance** [comment]
I'll add Rust style `for` statement like below:

```
for i: u32 in 0..MAX {
}
```

This style can't specify the range step. ( In Rust, it can be `(0..MAX).step_by(2)` )
So the additional notation to specify step ( or other incrementation ) is needed. 

```
for i: u32 in 0..MAX += 2 {
}
```

This is just idea.

**Comment by taichi-ishitani** [comment]
> for i: u32 in 0..MAX += 2

This notation looks like below.

```
for i: u32 in 0..(MAX += 2) 
```

So I think a separator symbol or keyword is needed.

```
for i: u32 in 0..MAX step_by 2
```

**Comment by dalance** [comment]
The syntax of range will be `EXPRESSION .. EXPRESSION`,
and `+=` will be statement. so `(MAX += 2)` is invalid.

On the other hand, the same symbol may be confusable.
The following notation can specify more operation.

```
0..MAX step += 2
0..MAX step -= 2
0..MAX step *= 2
0..MAX step /= 2
```

**Comment by taichi-ishitani** [comment]
> 0..MAX step += 2

This notation looks good for me.

**Comment by dalance** [comment]
Now for/if statement and for/if declaration ( a.k.a generate for/if ) are supported.
