### ISSUE TITLE
signed / unsigned representation

### ISSUE THREAD

**Issue by dalance** [dalance/veryl#85]
Signed / unsigned specifier is not implemented.

### `signed` / `unsigned` like SV

```
var a: signed logic[10];
var b: unsigned logic[10];
var c: logic[10]; // signed or unsigned ?
```

Some problems.

* bit long
* word length is not uniformed
* omitted case may be confusable

### `ilogic` / `ulogic`

This is the same as `isize` / `usize` in Rust.

```
var a: ilogic[10]; // signed logic in SV
var b: ulogic[10]; // unsigned logic in SV
var c: ibit  [10]; // signed bit in SV
var d: ubit  [10]; // unsigned bit in SV
```

This seems to be better than `signed` / `unsigned`?

**Comment by taichi-ishitani** [comment]
I think using a signed value is a special case than using a unsigned value.
Therefore, I prefer introducing the `signed` keyword as a type modifier like the `tri` keyword.

**Comment by dalance** [comment]
OK. It seems to be good that unsigned by default and `signed` is added only.
