### ISSUE TITLE
[Feature] Extend range comparison

### ISSUE THREAD

**Issue by taichi-ishitani** [dalance/veryl#87]
SystemVerilog supports only `a inside {[b:c]}`(`a >= b && a <= c`) as the range comparison.
I'd like to extend the rnage comparison feature to support other pairs of range operators.

* `a >= b && a <  c`
* `a >  b && a <= c`
* `a >= b && a <  c`

**Comment by dalance** [comment]
`a >= b && a <  c` and `a >= b && a <= c` are supported.
`a > b` type will be considered if there is any usecase later.
